<#
.SYNOPSIS
    Renders the WHOLE Grasshopper canvas of any Slop definition to a PNG.

.DESCRIPTION
    Builds the given Slop JSON through the standard loader, then calls the
    `GrasshopperCanvasImage` agent action, which renders the document's own
    bounding box (every component, group and scribble) via
    GH_Canvas.GenerateHiResImage — NOT a screen grab, so nothing is cropped by
    the window size or the operator's zoom level.

    This is the layout feedback loop for generated definitions: run it, LOOK at
    the PNG, then fix overlaps / unreadable clumps / stray groups in the
    generator instead of guessing from the JSON.

    The test JSON it writes (`slop-canvas-shot.json`) is scratch and is
    overwritten on every invocation; it is deliberately absent from every suite
    manifest.

.PARAMETER Definition
    Path to the Slop definition JSON to render. Required.

.PARAMETER Out
    Output PNG path. Default: workloads/rhino/canvas-shots/<def>.png
    (Deliberately OUTSIDE results/. Phase 2b gives results/ exactly two kinds of child -
    a test's evidence dir and a suite's rollup dir - and a third kind sitting alongside
    them is what makes a census wrong and a scan ambiguous.)

.PARAMETER Loader
    Slop loader fixture. Default: fixtures/bristle_slop_loader.gh (the loaders
    are byte-copies of one shell, so any of them builds any Slop JSON).

.PARAMETER Zoom
    Canvas zoom. Default 1.0. Automatically clamped down so the whole canvas
    fits a single tile; raise it on small definitions for crisper text.

.EXAMPLE
    ./scripts/slop-canvas-shot.ps1 -Definition C:\Repos\Bristle\tests\slop\10_bristle_seeds_studio.json
#>
param(
    [Parameter(Mandatory = $true)][string]$Definition,
    [string]$Out,
    [string]$Loader = 'fixtures/bristle_slop_loader.gh',
    [double]$Zoom = 1.0,
    [int]$Padding = 25,
    [switch]$KeepOpen
)

$ErrorActionPreference = 'Stop'
$canaryRoot = Split-Path $PSScriptRoot -Parent

if (-not (Test-Path $Definition)) { throw "Definition not found: $Definition" }
$defFull = (Resolve-Path $Definition).Path
$defName = [System.IO.Path]::GetFileNameWithoutExtension($defFull)

if (-not $Out) {
    $Out = Join-Path $canaryRoot "workloads\rhino\canvas-shots\$defName.png"
}
$outDir = Split-Path $Out -Parent
if ($outDir -and -not (Test-Path $outDir)) { New-Item -ItemType Directory -Force -Path $outDir | Out-Null }

# Slop reads the path from the loader's JsonPath panel; forward slashes only.
$defForPanel = $defFull -replace '\\', '/'
$outForAgent = ($Out -replace '\\', '/')

$test = [ordered]@{
    name        = 'slop-canvas-shot'
    workload    = 'rhino'
    description = "SCRATCH canvas render of $defName (generated by scripts/slop-canvas-shot.ps1). Not a gate test; absent from suites."
    setup       = [ordered]@{
        file     = $Loader
        viewport = [ordered]@{ width = 800; height = 600; projection = 'Perspective'; displayMode = 'Shaded' }
        commands = @()
        scene    = $null
        backend  = ''
        canvas   = $null
        vlm      = $null
    }
    runMode     = 'shared'
    recording   = ''
    checkpoints = @()
    actions     = @(
        [ordered]@{ type = 'WaitForGrasshopperSolution'; timeoutMs = 5000 },
        [ordered]@{ type = 'GrasshopperSetToggle'; nickname = 'Build'; value = $false },
        [ordered]@{ type = 'GrasshopperSetToggle'; nickname = 'Cleanup'; value = $true },
        [ordered]@{ type = 'WaitForGrasshopperSolution'; timeoutMs = 5000 },
        [ordered]@{ type = 'GrasshopperSetToggle'; nickname = 'Cleanup'; value = $false },
        [ordered]@{ type = 'WaitForGrasshopperSolution'; timeoutMs = 2000 },
        [ordered]@{ type = 'GrasshopperSetPanelText'; nickname = 'JsonPath'; text = $defForPanel },
        [ordered]@{ type = 'GrasshopperSetToggle'; nickname = 'Build'; value = $true },
        [ordered]@{ type = 'WaitForGrasshopperSolution'; timeoutMs = 60000 },
        [ordered]@{ type = 'GrasshopperCanvasImage'; path = $outForAgent; zoom = $Zoom; padding = $Padding }
    )
    asserts     = @(
        [ordered]@{ type = 'PanelEquals'; nickname = 'SlopSuccess'; text = 'True'; description = 'definition built before the canvas was rendered' }
    )
    keepOpenOnFailure = [bool]$KeepOpen
}

$testPath = Join-Path $canaryRoot 'workloads\rhino\tests\slop-canvas-shot.json'
($test | ConvertTo-Json -Depth 8) | Set-Content -Path $testPath -Encoding utf8
Write-Host "test  -> $testPath"
Write-Host "def   -> $defForPanel"
Write-Host "image -> $Out"

$exe = Join-Path $canaryRoot 'src\Canary.Harness\bin\Debug\net8.0-windows\canary.exe'
if (-not (Test-Path $exe)) { throw "canary.exe not built: $exe (run: dotnet build Canary.sln)" }

Push-Location $canaryRoot
try {
    $args = @('run', '--workload', 'rhino', '--test', 'slop-canvas-shot', '--headless')
    if ($KeepOpen) { $args += '--keep-open' }
    & $exe @args
}
finally { Pop-Location }

if (Test-Path $Out) {
    $img = Get-Item $Out
    Write-Host "OK: $($img.FullName) ($([math]::Round($img.Length / 1KB)) KB)"
} else {
    Write-Warning "No image at $Out - check the run output above."
}
